# Generated by Django 4.1 on 2022-08-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
